baseURL = 'https://miguoliang.com/zen_quant'
languageCode = 'zh_CN'
title = '分析工具 ｜ 禅宽量化'
theme = 'hugo-coder'

[params]
author = "禅宽量化"
keywords = "quantitative trading,stock analyze"

[params.googleTagManager]
id = "G-3XTC5Q3D4Y"

[[menu.main]]
name = "分析工具"
weight = 1
url = ""

[[menu.main]]
name = "产品净值"
weight = 2
url = "../net_value/"